image: node:20-alpine

stages:
  - build
  - deploy

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID
  VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

cache:
  paths:
    - .next/cache/
    - node_modules/

install_and_build:
  stage: build
  script:
    - npm install
    - npx prisma generate  # חשוב עבור ה-Types של הפרויקט שלך
    - npm run build
  artifacts:
    paths:
      - .next/
      - node_modules/

deploy_to_vercel:
  stage: deploy
  script:
    - npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - npx vercel build --prod --token=$VERCEL_TOKEN
    - npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  only:
    - main