image: node:20-alpine

stages:
  - build
  - deploy

cache:
  paths:
    - .next/cache/
    - node_modules/

# שלב הבנייה והבדיקה
install_and_build:
  stage: build
  script:
    - npm install
    - npx prisma generate  # חשוב עבור ה-Types של הפרויקט שלך
    - npm run build
  artifacts:
    paths:
      - .next/
      - node_modules/

# פריסה לסביבת Staging (ענף develop)
deploy_staging:
  stage: deploy
  script:
    - npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - npx vercel build --token=$VERCEL_TOKEN
    - npx vercel deploy --prebuilt --token=$VERCEL_TOKEN
  only:
    - develop

# פריסה לסביבת Production (ענף main) בדיקה קטנה לטובת הרצה של deploy_staging בפעם הראשונה
deploy_production:
  stage: deploy
  script:
    - npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - npx vercel build --prod --token=$VERCEL_TOKEN
    - npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  only:
    - main